from . import nodes as _nodes
from .apparel_nodes import NODE_CLASS_MAPPINGS as APPAREL_NODE_CLASS_MAPPINGS
from .apparel_nodes import NODE_DISPLAY_NAME_MAPPINGS as APPAREL_NODE_DISPLAY_NAME_MAPPINGS
from .smart_sticker import install_smart_sticker_filter

install_smart_sticker_filter(_nodes)

NODE_CLASS_MAPPINGS = dict(_nodes.NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(APPAREL_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = dict(_nodes.NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(APPAREL_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
